# -*- coding: utf-8 -*-
"""finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKjUrAUUag-IBmnzAbigi-UgcZjhHhhL
"""

"""
Single-cell project scaffold for: Personal Finance Chatbot (IBM Watson + Generative AI)

Paste this whole cell into a Jupyter/Colab notebook and run. It prints file contents (README, app scaffold, requirements).
You may adapt the cell to write files directly if you want.

Author: (your name)
"""
from textwrap import dedent

README = dedent("""\
# Personal Finance Chatbot

**Goal:** Build an intelligent conversational assistant using IBM Watson + generative AI to provide personalized financial guidance (savings, taxes, investments), auto-generated budget summaries, spending insights, and demographic-aware tone (student vs professional).

## Key Features
1. Personalized Financial Guidance (profile-aware)
2. AI-Generated Budget Summaries (monthly, category breakdown, suggested allocations)
3. Spending Insights & Actionable Recommendations
4. Demographic-Aware Communication (student / professional tone & complexity)
5. Conversational NLP using IBM Watson + HuggingFace (or other LLMs)

## Tech Stack
- Python 3.10+
- Streamlit (frontend)
- IBM Watson SDK (Assistant, NLU / Discovery) — for enterprise NLP & connectors
- HuggingFace Transformers or hosted LLM (for budget summarization, embeddings, or generation)
- Optionally: OpenAI or other LLM endpoints if permitted
- Persistence: SQLite or small document DB (for conversation history & user profiles)
- Optional UI toolkit: Granite (if used in your org) — integrate to improve styling

## High-level Architecture
User (Streamlit UI)
    ↕
Frontend logic (Streamlit)
    ↕
Conversation handler
    ↕
Policy & Business logic (profile, budget engine, insights)
    ↕
LLM / Watson calls (IBM Watson Assistant / NLU / Generative) + HF models
    ↕
Storage: SQLite / JSON files for user profile & budgets

## Milestones
1. M1 — Minimal chat flow (Streamlit + mock responses)
2. M2 — Integrate Watson Assistant for intent/context handling
3. M3 — Add budget upload / expense parser & auto-summary (HuggingFace model for NER if needed)
4. M4 — Demographic tone adapter & A/B testing
5. M5 — Security, logging, deployment (Docker, IBM Cloud / Heroku / Streamlit Cloud)

## Security & Privacy
- NEVER store PII unencrypted.
- Use environment variables for API keys.
- Provide clear privacy notice and opt-in for storing financial data.

## Run / dev
1. Fill ENV vars: IBM_API_KEY, IBM_URL, HF_API_KEY (or chosen LLM)
2. Install requirements (see requirements.txt below)
3. Run: `streamlit run app.py`
""")

APP_PY = dedent("""\
# app.py - Streamlit starter for Personal Finance Chatbot
# NOTE: Replace placeholders with your own IBM Watson / HF credentials.
# This is a working scaffold demonstrating UI, tone adaptation, and simple budget summarization.

import os
import streamlit as st
import json
from datetime import datetime
from typing import Dict, Any, List

# === Helper: load env (replace with secure secret management in prod) ===
IBM_API_KEY = os.getenv("IBM_API_KEY", "<YOUR_IBM_API_KEY>")
IBM_URL = os.getenv("IBM_URL", "<YOUR_IBM_URL>")
HF_API_KEY = os.getenv("HF_API_KEY", "<YOUR_HF_API_KEY>")

# === Simple local persistence (dev only) ===
PROFILE_DB = "profiles.json"

def load_profiles():
    try:
        with open(PROFILE_DB, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_profiles(profiles):
    with open(PROFILE_DB, "w") as f:
        json.dump(profiles, f, indent=2)

# === Tone adaptation helper ===
def adapt_tone(base_text: str, user_type: str) -> str:
    """
    Adapt tone: 'student' => simpler, friendly; 'professional' => concise, formal.
    This function demonstrates local adaptation. In production, send a 'tone' signal to your LLM.
    """
    if user_type == "student":
        return f"Hey! {base_text} (explained simply — let me know if you want examples)."
    elif user_type == "professional":
        return f"{base_text} (recommended actions prioritized; for deeper analysis, request 'detailed')."
    else:
        return base_text

# === Mock / example: budget summarizer ===
def summarize_budget(transactions: List[Dict[str,Any]]) -> Dict[str,Any]:
    """
    transactions: list of {'date': 'YYYY-MM-DD', 'category': 'food', 'amount': 12.50}
    Returns aggregated monthly totals and simple suggestions.
    """
    totals = {}
    total_spent = 0.0
    for tx in transactions:
        cat = tx.get("category","other")
        amt = float(tx.get("amount",0.0))
        totals[cat] = totals.get(cat, 0.0) + amt
        total_spent += amt
    suggestions = []
    # naive suggestions
    for cat, amt in sorted(totals.items(), key=lambda x: -x[1])[:3]:
        suggestions.append(f"Top spending: {cat} — ${amt:.2f}. Consider trimming by 10% if discretionary.")
    # example allocation guideline:
    suggestions.append(f"Total monthly spend: ${total_spent:.2f}. Consider a 50/30/20 guideline: essentials/needs/savings.")
    return {"totals": totals, "total": total_spent, "suggestions": suggestions}

# === Placeholders for IBM Watson / HF calls ===
def call_ibm_assistant(user_message: str, context: Dict[str,Any]) -> Dict[str,Any]:
    """
    TODO: Replace this mock with actual IBM Assistant SDK calls.
    Example using `ibm-watson`:
      from ibm_watson import AssistantV2
      assistant = AssistantV2(version='2023-11-01', iam_apikey=IBM_API_KEY, url=IBM_URL)
      response = assistant.message(...)

    Return structure: {'reply': str, 'intent': 'advice', 'entities': {...}}
    """
    # Mock reply
    reply = f"[IBM Assistant MOCK] I understand you asked: {user_message[:120]}"
    intent = "ask_budget" if "budget" in user_message.lower() else "ask_finance"
    return {"reply": reply, "intent": intent, "entities": {}}

def call_generation_model(prompt: str, tone: str = "neutral") -> str:
    """
    TODO: Replace this with a real HF or LLM call. If using HuggingFace Inference API:
      import requests
      headers = {"Authorization": f"Bearer {HF_API_KEY}"}
      r = requests.post("https://api-inference.huggingface.co/models/<model>", json={"inputs": prompt}, headers=headers)
      return r.json()

    This method will combine financial logic + tone.
    """
    return f"[LLM MOCK - tone={tone}] {prompt}"

# === Streamlit UI ===
st.set_page_config(page_title="Personal Finance Chatbot", page_icon="💬", layout="centered")
st.title("Personal Finance Chatbot (prototype)")

# Sidebar: profile creation / selection
st.sidebar.header("User Profile")
profiles = load_profiles()
profile_names = list(profiles.keys())
selected = st.sidebar.selectbox("Select profile", ["<new>"] + profile_names)
if selected == "<new>":
    name = st.sidebar.text_input("Name")
    user_type = st.sidebar.selectbox("User type", ["student", "professional", "other"])
    income = st.sidebar.number_input("Monthly income (optional)", min_value=0.0, value=0.0, step=100.0)
    if st.sidebar.button("Create profile"):
        if not name:
            st.sidebar.error("Give a name")
        else:
            profiles[name] = {"type": user_type, "income": income, "created": str(datetime.utcnow())}
            save_profiles(profiles)
            st.sidebar.success(f"Profile {name} created. Re-run or select it from the list.")
            st.experimental_rerun()
else:
    profile = profiles.get(selected, {})
    st.sidebar.write("Type:", profile.get("type"))
    st.sidebar.write("Income:", profile.get("income"))

# Main chat area
if selected != "<new>":
    st.subheader(f"Chat as: {selected}")
    user_type = profiles[selected].get("type", "other")

    # Chat history in session_state
    if "history" not in st.session_state:
        st.session_state.history = []

    # Input and send
    user_input = st.text_input("Ask a finance question (savings, tax, budgets...)", key="user_input")
    if st.button("Send"):
        if user_input.strip():
            # 1. Send to IBM Assistant (intent/entity detection + context)
            ibm_resp = call_ibm_assistant(user_input, context={"profile": profiles[selected]})
            intent = ibm_resp.get("intent", "unknown")
            assistant_reply = ibm_resp.get("reply", "")

            # 2. If user provided transaction data in a simple format, parse and summarize
            # Very simple detect: if user_input contains 'transactions:' followed by JSON-like list
            budget_summary = None
            if "transactions:" in user_input.lower():
                # naive parser: expect JSON after 'transactions:'
                try:
                    idx = user_input.lower().index("transactions:")
                    json_part = user_input[idx + len("transactions:"):].strip()
                    transactions = json.loads(json_part)
                    budget_summary = summarize_budget(transactions)
                    # generate friendly summary using LLM (mock)
                    gen_prompt = f"Create a short budget summary for user_type={user_type} based on totals {budget_summary['totals']}"
                    generated_text = call_generation_model(gen_prompt, tone=user_type)
                    assistant_reply = adapt_tone(generated_text, user_type)
                except Exception as e:
                    assistant_reply = adapt_tone("Sorry, I couldn't parse your transactions. Please supply a JSON list of transactions.", user_type)

            else:
                # 3. Otherwise generate advice using LLM (mock)
                gen_prompt = f"User type: {user_type}. Intent: {intent}. Question: {user_input}. Provide practical, concise guidance."
                generated = call_generation_model(gen_prompt, tone=user_type)
                assistant_reply = adapt_tone(generated, user_type)

            # Append to history
            st.session_state.history.append({"from":"user", "text": user_input})
            st.session_state.history.append({"from":"bot", "text": assistant_reply})

    # display history
    for msg in st.session_state.history:
        if msg["from"] == "user":
            st.markdown(f"**You:** {msg['text']}")
        else:
            st.markdown(f"**Bot:** {msg['text']}")

    # Quick actions
    st.markdown("---")
    st.subheader("Quick actions")
    if st.button("Show sample budget template"):
        st.code(dedent('''\
            [
              {"date":"2025-11-01","category":"food","amount":12.5},
              {"date":"2025-11-02","category":"transport","amount":4.75},
              {"date":"2025-11-03","category":"rent","amount":450}
            ]
        '''), language="json")
    if st.button("Example: Analyze this sample transactions (demo)"):
        sample = [
          {"date":"2025-11-01","category":"food","amount":120.5},
          {"date":"2025-11-02","category":"entertainment","amount":60},
          {"date":"2025-11-15","category":"rent","amount":900},
          {"date":"2025-11-20","category":"transport","amount":50},
        ]
        summary = summarize_budget(sample)
        st.json(summary)
else:
    st.write("Create or select a profile on the left to start chatting.")

st.markdown("---")
st.write("Dev notes: Replace `call_ibm_assistant` and `call_generation_model` with production SDK calls (ibm-watson + HF or preferred LLM). Use secure secret store for API keys.")
""")

REQUIREMENTS = dedent("""\
streamlit>=1.24
ibm-watson>=6.0.0
requests>=2.28
transformers>=4.30
torch  # optional depending on model choice
pandas
sqlite-utils  # optional: small DB utilities
""")

print("==== README.md ====")
print(README)
print("==== app.py ====")
print(APP_PY)
print("==== requirements.txt ====")
print(REQUIREMENTS)

print(dedent("""\
==== NEXT STEPS (developer checklist) ====
1) Create environment, install requirements:
   python -m venv env
   source env/bin/activate
   pip install -r requirements.txt

2) Replace mocks:
   - Implement `call_ibm_assistant` using ibm-watson AssistantV2 (or AssistantV1 if needed).
   - For NLU: consider `NaturalLanguageUnderstandingV1` for entity extraction, or use Assistant's built-in NLU.
   - Implement `call_generation_model` to call a hosted LLM (HuggingFace Inference API, or IBM's generative models if available).

3) Implement secure storage for profiles & conversation history (encrypted DB or cloud storage).
4) Add expense uploader: CSV / bank export parser + category mapping.
5) Add test cases & CI; containerize (Docker).
6) Consider compliance & legal (finance/tax advice disclaimers).
7) Deploy to Streamlit Cloud or IBM Cloud; add monitoring and rate-limits.

If you want, I can:
- convert this to a GitHub repo layout and produce each file content separately,
- or replace the mocks with actual IBM Assistant example code (I can add that directly).
"""))



# --- Personal Finance Chatbot: Single-Cell Project Scaffold (Error-Free Version) ---

from textwrap import dedent
import json

# ========== README ==========
README = dedent("""
# Personal Finance Chatbot

This project uses Python, Streamlit, IBM Watson, HuggingFace, and Granite UI ideas
to build a personalized financial guidance chatbot.

## Features
- Personalized guidance on savings, taxes, investments
- Budget summarization
- Spending insight generation
- Demographic-aware tone (student vs professional)
- Conversational NLP with IBM Watson and HuggingFace models
""")

# ========== app.py CONTENT ==========
APP_PY = dedent("""
import os
import json
import streamlit as st
from datetime import datetime
from textwrap import dedent

# Dummy environment variables (replace with real keys)
IBM_API_KEY = os.getenv("IBM_API_KEY", "YOUR_IBM_KEY")
IBM_URL = os.getenv("IBM_URL", "YOUR_IBM_URL")
HF_API_KEY = os.getenv("HF_API_KEY", "YOUR_HF_KEY")

PROFILE_DB = "profiles.json"

def load_profiles():
    try:
        with open(PROFILE_DB, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_profiles(data):
    with open(PROFILE_DB, "w") as f:
        json.dump(data, f, indent=2)

def adapt_tone(text, user_type):
    if user_type == "student":
        return "Hey! " + text + " (explained simply)."
    if user_type == "professional":
        return text + " (professional summary)."
    return text

def summarize_budget(transactions):
    totals = {}
    total = 0
    for tx in tra

# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")



# ---------- ERROR-FREE SINGLE CELL PROJECT SCAFFOLD ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def summarize_budget(transactions):",
"    totals = {}",
"    total = 0",
"    for tx in transactions:",
"        cat = tx['category']",
"        amt = float(tx['amount'])",
"        totals[cat] = totals.get(cat, 0) + amt",
"        total += amt",
"    suggestions = [f'Total spent: ${total:.2f}. Consider 50/30/20 rule.']",
"    return {'totals': totals, 'total': total, 'suggestions': suggestions}",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return f'[LLM MOCK | tone={tone}] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as:', selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(f'**{sender}:** {msg}')",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

print("===== README.md =====")
for line in README:
    print(line)

print("\n===== app.py =====")
for line in APP_PY:
    print(line)

print("\n===== requirements.txt =====")
for line in REQUIREMENTS:
    print(line)

print("\n===== SUCCESS: Everything generated with zero syntax errors =====")

# --- Create README, app.py, requirements.txt AUTOMATICALLY ---

README = """# Personal Finance Chatbot

Features:
- Personalized financial guidance
- Budget summaries
- Spending insights
- Tone adaptation (student vs professional)
- IBM Watson + HuggingFace NLP

Run using: streamlit run app.py
"""

APP_PY = """import os
import json
import streamlit as st
from datetime import datetime

IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')
IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')
HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')

PROFILE_DB = 'profiles.json'

def load_profiles():
    try:
        with open(PROFILE_DB, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_profiles(data):
    with open(PROFILE_DB, 'w') as f:
        json.dump(data, f, indent=2)

def adapt_tone(text, user_type):
    if user_type == 'student':
        return 'Hey! ' + text + ' (explained simply).'
    if user_type == 'professional':
        return text + ' (professional summary).'
    return text

def call_ibm_assistant(msg, ctx):
    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}

def call_generation_model(prompt, tone):
    return f'[LLM MOCK | tone={tone}] ' + prompt

# ---- UI ----
st.title('Personal Finance Chatbot')

profiles = load_profiles()
selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))

if selected == '<new>':
    name = st.sidebar.text_input('Name')
    utype = st.sidebar.selectbox('Type', ['student','professional','other'])
    income = st.sidebar.number_input('Income', min_value=0.0)
    if st.sidebar.button('Create'):
        profiles[name] = {'type': utype, 'income': income, 'creat

# ---------- ERROR-PROOF FILE CREATOR (NO TRIPLE QUOTES ANYWHERE) ----------

# README content
README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

# app.py content
APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent

# ---------- ERROR-PROOF FILE CREATOR ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv(\"IBM_API_KEY\", \"YOUR_IBM_KEY\")",
"IBM_URL = os.getenv(\"IBM_URL\", \"YOUR_IBM_URL\")",
"HF_API_KEY = os.getenv(\"HF_API_KEY\", \"YOUR_HF_KEY\")",
"",
"PROFILE_DB = \"profiles.json\"",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, \"r\") as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, \"w\") as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == \"student\":",
"        return \"Hey! \" + text + \" (explained simply).\"",
"    if user_type == \"professional\":",
"        return text + \" (professional summary).\"",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {\"reply\": \"[IBM MOCK RESPONSE] You asked: \" + msg, \"intent\": \"finance\"}",
"",
"def call_generation_model(prompt, tone):",
"    return \"[LLM MOCK | tone=\" + tone + \"] \" + prompt",
"",
"st.title(\"Personal Finance Chatbot\")",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox(\"Profile\", [\"<new>\"] + list(profiles.keys()))",
"",
"if selected == \"<new>\":",
"    name = st.sidebar.text_input(\"Name\")",
"    utype = st.sidebar.selectbox(\"Type\", [\"student\",\"professional\",\"other\"])",
"    income = st.sidebar.number_input(\"Income\", min_value=0.0)",
"    if st.sidebar.button(\"Create\"):",
"        profiles[name] = {\"type\": utype, \"income\": income, \"created\": str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success(\"Profile created. Reload.\")",
"",
"else:",
"    profile = profiles[selected]",
"    st.write(\"### Chat as:\", selected)",
"",
"    if \"history\" not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input(\"Ask something about finances:\")",
"",
"    if st.button(\"Send\"):",
"        ibm = call_ibm_assistant(txt, {\"profile\": profile})",
"        tone = profile[\"type\"]",
"        reply = call_generation_model(ibm[\"reply\"], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append((\"You\", txt))",
"        st.session_state.history.append((\"Bot\", reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(\"**\" + sender +**

# ---------- GUARANTEED ERROR-FREE FILE CREATOR ----------

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'reply': '[IBM MOCK RESPONSE] You asked: ' + msg, 'intent': 'finance'}",
"",
"def call_generation_model(prompt, tone):",
"    return '[LLM MOCK | tone=' + tone + '] ' + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as: ' + selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(sender + ': ' + msg)",
]

REQUIREMENTS = [
"streamlit",
"ibm-watson",
"requests",
"transformers",
"torch",
"pandas",
]

# ---- Write Files ----
with open("README.md", "w") as f:
    for line in README:
        f.write(line + "\n")

with open("app.py", "w") as f:
    for line in APP_PY:
        f.write(line + "\n")

with open("requirements.txt", "w") as f:
    for line in REQUIREMENTS:
        f.write(line + "\n")

print("All files created successfully without any syntax errors!")
print("Run the app using: streamlit run app.py")

README = [
"# Personal Finance Chatbot",
"",
"Features:",
"- Personalized financial guidance",
"- Budget summaries",
"- Spending insights",
"- Tone adaptation (student vs professional)",
"- IBM Watson + HuggingFace NLP",
"",
"Run using: streamlit run app.py",
]

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {'

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {\"reply\": \"[IBM MOCK RESPONSE] You asked: \" + msg, \"intent\": \"finance\"}",
"",
"def call_generation_model(prompt, tone):",
"    return \"[LLM MOCK | tone=\" + tone + \"] \" + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as: ' + selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(sender + ': ' + ms

APP_PY = [
"import os",
"import json",
"import streamlit as st",
"from datetime import datetime",
"",
"IBM_API_KEY = os.getenv('IBM_API_KEY', 'YOUR_IBM_KEY')",
"IBM_URL = os.getenv('IBM_URL', 'YOUR_IBM_URL')",
"HF_API_KEY = os.getenv('HF_API_KEY', 'YOUR_HF_KEY')",
"",
"PROFILE_DB = 'profiles.json'",
"",
"def load_profiles():",
"    try:",
"        with open(PROFILE_DB, 'r') as f:",
"            return json.load(f)",
"    except FileNotFoundError:",
"        return {}",
"",
"def save_profiles(data):",
"    with open(PROFILE_DB, 'w') as f:",
"        json.dump(data, f, indent=2)",
"",
"def adapt_tone(text, user_type):",
"    if user_type == 'student':",
"        return 'Hey! ' + text + ' (explained simply).'",
"    if user_type == 'professional':",
"        return text + ' (professional summary).'",
"    return text",
"",
"def call_ibm_assistant(msg, ctx):",
"    return {\"reply\": \"[IBM MOCK RESPONSE] You asked: \" + msg, \"intent\": \"finance\"}",
"",
"def call_generation_model(prompt, tone):",
"    return \"[LLM MOCK | tone=\" + tone + \"] \" + prompt",
"",
"st.title('Personal Finance Chatbot')",
"profiles = load_profiles()",
"selected = st.sidebar.selectbox('Profile', ['<new>'] + list(profiles.keys()))",
"",
"if selected == '<new>':",
"    name = st.sidebar.text_input('Name')",
"    utype = st.sidebar.selectbox('Type', ['student','professional','other'])",
"    income = st.sidebar.number_input('Income', min_value=0.0)",
"    if st.sidebar.button('Create'):",
"        profiles[name] = {'type': utype, 'income': income, 'created': str(datetime.utcnow())}",
"        save_profiles(profiles)",
"        st.sidebar.success('Profile created. Reload.')",
"",
"else:",
"    profile = profiles[selected]",
"    st.write('### Chat as: ' + selected)",
"",
"    if 'history' not in st.session_state:",
"        st.session_state.history = []",
"",
"    txt = st.text_input('Ask something about finances:')",
"",
"    if st.button('Send'):",
"        ibm = call_ibm_assistant(txt, {'profile': profile})",
"        tone = profile['type']",
"        reply = call_generation_model(ibm['reply'], tone)",
"        reply = adapt_tone(reply, tone)",
"        st.session_state.history.append(('You', txt))",
"        st.session_state.history.append(('Bot', reply))",
"",
"    for sender, msg in st.session_state.history:",
"        st.write(sender + ': ' + msg)",
]